services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  
    volumes:
      - ollama_data:/root/.ollama 
    deploy:
      resources:
        limits:
          memory: 2.5G
    networks:
      - ai-network  
          
  ai-agent:
    image: fekom/ai-agent:v2
    depends_on:
      ollama:
        condition: service_started
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - 9200:9200
    networks:
      - ai-network
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

networks:
   ai-network:
     driver: bridge

volumes:
  ollama_data: